listener 1883
allow_anonymous false

auth_plugin /mosquitto/go-auth.so

auth_opt_backends http
auth_opt_http_host totem-api
auth_opt_http_port 8000
auth_opt_http_params_mode json
auth_opt_http_getuser_uri /api/internal/mqtt/auth
auth_opt_http_superuser_uri /api/internal/mqtt/superuser
auth_opt_http_aclcheck_uri /api/internal/mqtt/acl
