export const s = {
  page: {
    minHeight: '100dvh',
    background: '#111',
    color: '#fff',
    fontFamily: 'system-ui, sans-serif',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    boxSizing: 'border-box',
  },
  header: {
    width: '100%',
    maxWidth: '480px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '20px 16px',
  },
  container: {
    width: '100%',
    maxWidth: '480px',
    padding: '0 16px 40px',
  },
  logo: {
    fontSize: '20px',
    fontWeight: '700',
    letterSpacing: '3px',
    margin: 0,
  },
  title: {
    fontSize: '18px',
    fontWeight: '600',
    margin: '0 0 16px',
  },
  muted: {
    color: '#555',
    fontSize: '14px',
    margin: '8px 0',
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    width: '100%',
  },
  input: {
    background: '#1e1e1e',
    border: '1px solid #333',
    borderRadius: '10px',
    color: '#fff',
    padding: '12px 14px',
    fontSize: '14px',
    outline: 'none',
    width: '100%',
    boxSizing: 'border-box',
  },
  btn: {
    background: '#27ae60',
    border: 'none',
    borderRadius: '10px',
    color: '#fff',
    padding: '13px',
    fontSize: '14px',
    fontWeight: '600',
    cursor: 'pointer',
    width: '100%',
  },
  btnGhost: {
    background: 'transparent',
    border: 'none',
    color: '#888',
    fontSize: '14px',
    cursor: 'pointer',
    padding: '4px 0',
  },
  btnSm: {
    background: '#1e1e1e',
    border: '1px solid #333',
    borderRadius: '8px',
    color: '#fff',
    padding: '8px 16px',
    fontSize: '13px',
    cursor: 'pointer',
    whiteSpace: 'nowrap',
  },
  card: {
    background: '#1a1a1a',
    border: '1px solid #2a2a2a',
    borderRadius: '12px',
    padding: '16px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '10px',
  },
  cardTitle: {
    margin: '0 0 4px',
    fontWeight: '600',
    fontSize: '15px',
  },
  cardSub: {
    margin: 0,
    color: '#666',
    fontSize: '12px',
    textTransform: 'uppercase',
    letterSpacing: '1px',
  },
  error: {
    color: '#e74c3c',
    fontSize: '13px',
    margin: '4px 0',
  },
  link: {
    color: '#666',
    fontSize: '13px',
    textAlign: 'center',
    margin: 0,
  },
  a: {
    color: '#27ae60',
    textDecoration: 'none',
  },
  timestamp: {
    fontSize: '12px',
    color: '#555',
  },
  pumpWrap: {
    display: 'flex',
    justifyContent: 'center',
    marginBottom: '40px',
    marginTop: '16px',
  },
  pumpBtn: (on, loading) => ({
    width: '200px',
    height: '200px',
    borderRadius: '50%',
    border: 'none',
    cursor: loading ? 'wait' : 'pointer',
    background: on ? '#c0392b' : '#27ae60',
    boxShadow: on ? '0 0 48px rgba(192,57,43,0.5)' : '0 0 48px rgba(39,174,96,0.4)',
    transition: 'background 0.3s, box-shadow 0.3s, transform 0.1s',
    transform: loading ? 'scale(0.96)' : 'scale(1)',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '6px',
    WebkitTapHighlightColor: 'transparent',
  }),
  pumpAction: {
    fontSize: '24px',
    fontWeight: '700',
    color: '#fff',
    letterSpacing: '1px',
  },
  pumpStatus: {
    fontSize: '11px',
    color: 'rgba(255,255,255,0.7)',
    letterSpacing: '2px',
  },
  sensors: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '12px',
  },
  sensor: {
    background: '#1e1e1e',
    borderRadius: '14px',
    padding: '20px 16px',
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  sensorValue: {
    fontSize: '26px',
    fontWeight: '600',
  },
  sensorLabel: {
    fontSize: '11px',
    color: '#555',
    letterSpacing: '1px',
  },
  apiKeyBox: {
    background: '#1a2a1a',
    border: '1px solid #27ae60',
    borderRadius: '12px',
    padding: '20px',
    marginTop: '16px',
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  apiKey: {
    background: '#111',
    borderRadius: '8px',
    padding: '12px',
    fontSize: '12px',
    color: '#27ae60',
    wordBreak: 'break-all',
    fontFamily: 'monospace',
  },
}
